// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkqujnmtvypokeemfltj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprcXVqbm10dnlwb2tlZW1mbHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDYwMzIsImV4cCI6MjA2OTcyMjAzMn0.Q4mFu4xBtfjdba_c9_JfK45nJe1H9pBnKWKbbF2yDuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});